alphabetlist = []
x = int(input("How many words? "))

# number = input("How many words? ")
# type(number)

if x < 2:
    print()
    "You must have more than 1 word!"
    x = int(input("How many words? "))

if x == 2:
    toadd = input("1> ")
    alphabetlist.append(toadd)
    toadd = input("2> ")
    alphabetlist.append(toadd)

if x == 3:
    toadd = input("1> ")
    alphabetlist.append(toadd)
    toadd = input("2> ")
    alphabetlist.append(toadd)
    toadd = input("3> ")
    alphabetlist.append(toadd)

if x == 4:
    toadd = input("1> ")
    alphabetlist.append(toadd)
    toadd = input("2> ")
    alphabetlist.append(toadd)
    toadd = input("3> ")
    alphabetlist.append(toadd)
    toadd = input("4> ")
    alphabetlist.append(toadd)

if x == 5:
    toadd = input("1> ")
    alphabetlist.append(toadd)
    toadd = input("2> ")
    alphabetlist.append(toadd)
    toadd = input("3> ")
    alphabetlist.append(toadd)
    toadd = input("4> ")
    alphabetlist.append(toadd)
    toadd = input("5> ")
    alphabetlist.append(toadd)

if x == 6:
    toadd = input("1> ")
    alphabetlist.append(toadd)
    toadd = input("2> ")
    alphabetlist.append(toadd)
    toadd = input("3> ")
    alphabetlist.append(toadd)
    toadd = input("4> ")
    alphabetlist.append(toadd)
    toadd = input("5> ")
    alphabetlist.append(toadd)
    toadd = input("6> ")
    alphabetlist.append(toadd)

if x == 7:
    toadd = input("1> ")
    alphabetlist.append(toadd)
    toadd = input("2> ")
    alphabetlist.append(toadd)
    toadd = input("3> ")
    alphabetlist.append(toadd)
    toadd = input("4> ")
    alphabetlist.append(toadd)
    toadd = input("5> ")
    alphabetlist.append(toadd)
    toadd = input("6> ")
    alphabetlist.append(toadd)
    toadd = input("7> ")
    alphabetlist.append(toadd)

if x == 8:
    toadd = input("1> ")
    alphabetlist.append(toadd)
    toadd = input("2> ")
    alphabetlist.append(toadd)
    toadd = input("3> ")
    alphabetlist.append(toadd)
    toadd = input("4> ")
    alphabetlist.append(toadd)
    toadd = input("5> ")
    alphabetlist.append(toadd)
    toadd = input("6> ")
    alphabetlist.append(toadd)
    toadd = input("7> ")
    alphabetlist.append(toadd)
    toadd = input("8> ")
    alphabetlist.append(toadd)

if x == 9:
    toadd = input("1> ")
    alphabetlist.append(toadd)
    toadd = input("2> ")
    alphabetlist.append(toadd)
    toadd = input("3> ")
    alphabetlist.append(toadd)
    toadd = input("4> ")
    alphabetlist.append(toadd)
    toadd = input("5> ")
    alphabetlist.append(toadd)
    toadd = input("6> ")
    alphabetlist.append(toadd)
    toadd = input("7> ")
    alphabetlist.append(toadd)
    toadd = input("8> ")
    alphabetlist.append(toadd)
    toadd = input("9> ")
    alphabetlist.append(toadd)

if x == 10:
    toadd = input("1> ")
    alphabetlist.append(toadd)
    toadd = input("2> ")
    alphabetlist.append(toadd)
    toadd = input("3> ")
    alphabetlist.append(toadd)
    toadd = input("4> ")
    alphabetlist.append(toadd)
    toadd = input("5> ")
    alphabetlist.append(toadd)
    toadd = input("6> ")
    alphabetlist.append(toadd)
    toadd = input("7> ")
    alphabetlist.append(toadd)
    toadd = input("8> ")
    alphabetlist.append(toadd)
    toadd = input("9> ")
    alphabetlist.append(toadd)
    toadd = input("10> ")
    alphabetlist.append(toadd)

if x > 10:
    print()
    "Too many words!"
    x = int(input("How many words? "))

alphabetlist.sort()
print()
